name: Continuous Integration

on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: 8.0.x
      
    - name: Restore
      run: dotnet restore src/TempMail.sln
      
    - name: Build
      run: dotnet build src/TempMail.sln --configuration Release --no-restore

    - name: Test
      env:
        TM_API_URI: ${{ secrets.TM_API_URI }}
        TM_SMTP_FROM: ${{ secrets.TM_SMTP_FROM }}
        TM_SMTP_HOST: ${{ secrets.TM_SMTP_HOST }}
        TM_SMTP_LOGIN: ${{ secrets.TM_SMTP_LOGIN }}
        TM_SMTP_PASSWORD: ${{ secrets.TM_SMTP_PASSWORD }}
        TM_SMTP_PORT: ${{ secrets.TM_SMTP_PORT }}       
      run: dotnet test src/TempMail.Tests/TempMail.Tests.csproj --no-restore --verbosity normal
    
    - name: Pack
      run: dotnet pack src/TempMail/TempMail.csproj --output nuget-packages --configuration Release
    
    - name: Publish
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

